In [1]:
import numpy as np


In [2]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [3]:
np.save('myarray', arr)

In [4]:
arr = np.arrange(10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [5]:
arr = np.arange(10)

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [8]:
arr1 = np.load('myarray.npy')
arr1

array([0, 1, 2, 3, 4])

In [9]:
arr2 = arr

In [10]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.savez('ziparray.npz', x=arr1, y=arr2)

In [12]:
archive_array = np.load('ziparray.npz')

In [13]:
archive_Array.x

NameError: name 'archive_Array' is not defined

In [14]:
archive_Array['x']

NameError: name 'archive_Array' is not defined

In [15]:
archive_Array


NameError: name 'archive_Array' is not defined

In [18]:
archive_array


In [19]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [20]:
arr = np.array([[1,2,3], [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.savetxt('mytextarray.txt', arr, delimiter=',')