In [1]:
import numpy as np


In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)

In [7]:
A

array([ 1.35204286,  1.75466057,  1.95704194, -0.58571731,  1.51806096,
        0.40619513,  0.19651697,  0.6819911 , -0.04964489,  1.39709268])

In [8]:
B = np.random.randn(10)

In [9]:
B

array([-2.26229202,  0.73162076,  0.91356428, -0.699963  ,  1.37948571,
       -0.13917006, -0.68480659,  2.12904463, -1.01835974,  1.23877984])

In [10]:
#binary functions
np.add(A,B)

array([-0.91024917,  2.48628134,  2.87060622, -1.28568031,  2.89754667,
        0.26702507, -0.48828961,  2.81103573, -1.06800462,  2.63587252])

In [11]:
np.maximum(A,B)

array([ 1.35204286,  1.75466057,  1.95704194, -0.58571731,  1.51806096,
        0.40619513,  0.19651697,  2.12904463, -0.04964489,  1.39709268])