In [1]:
import numpy as np
import pandas as pd
from pandas import Series as s, DataFrame as df

In [2]:
arr1 = np.arange(9).reshape(3,3)

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate([arr1, arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1, arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = s([0,1,2], index=['T', 'U', 'N'])
ser2 = s([3,4], index=['X', 'Y'])


In [7]:
ser1

T    0
U    1
N    2
dtype: int64

In [8]:
ser2

X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1, ser2])

T    0
U    1
N    2
X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1, ser2], axis=1)

0    1
N  2.0  NaN
T  0.0  NaN
U  1.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [11]:
pd.concat([ser1, ser2], axis=0)

T    0
U    1
N    2
X    3
Y    4
dtype: int64

In [12]:
pd.concat([ser1, ser2], keys=['cat1', 'cat2'])

cat1  T    0
      U    1
      N    2
cat2  X    3
      Y    4
dtype: int64

In [13]:
pd.concat([ser1, ser2], keys=['cat1', 'cat2'], axis=1)

cat1  cat2
N   2.0   NaN
T   0.0   NaN
U   1.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [14]:
df1 = df(np.random.randn(4,3), columns=['X', 'Y', 'Z'])
df2 = df(np.random.randn(3,3), columns=['Y', 'Q', 'X'])

In [15]:
df1

X         Y         Z
0 -0.214896  0.459882 -0.044649
1 -0.351177  2.428907 -1.135306
2  0.321862 -1.518776 -0.046863
3  0.493483  0.379961  1.370441

In [16]:
df2

Y         Q         X
0  0.157702  0.812252  0.558010
1 -0.762893  0.390417  0.112561
2 -0.624651 -0.320724  0.312374

In [17]:
pd.concat([df1, df2])

Q         X         Y         Z
0       NaN -0.214896  0.459882 -0.044649
1       NaN -0.351177  2.428907 -1.135306
2       NaN  0.321862 -1.518776 -0.046863
3       NaN  0.493483  0.379961  1.370441
0  0.812252  0.558010  0.157702       NaN
1  0.390417  0.112561 -0.762893       NaN
2 -0.320724  0.312374 -0.624651       NaN

In [18]:
pd.concat([df1, df2], axis=1)

X         Y         Z         Y         Q         X
0 -0.214896  0.459882 -0.044649  0.157702  0.812252  0.558010
1 -0.351177  2.428907 -1.135306 -0.762893  0.390417  0.112561
2  0.321862 -1.518776 -0.046863 -0.624651 -0.320724  0.312374
3  0.493483  0.379961  1.370441       NaN       NaN       NaN

In [19]:
pd.concat([df1, df2], ignore_index=True)

Q         X         Y         Z
0       NaN -0.214896  0.459882 -0.044649
1       NaN -0.351177  2.428907 -1.135306
2       NaN  0.321862 -1.518776 -0.046863
3       NaN  0.493483  0.379961  1.370441
4  0.812252  0.558010  0.157702       NaN
5  0.390417  0.112561 -0.762893       NaN
6 -0.320724  0.312374 -0.624651       NaN